# Generated by Django 5.2.8 on 2026-02-15 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='credit_card',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
    ]
