# Generated by Django 5.2.8 on 2026-01-10 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name=20)),
                ('discription', models.TextField()),
                ('condition', models.TextField()),
                ('seoblock', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.seoblock')),
            ],
        ),
        migrations.CreateModel(
            name='CinemaThourghtImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_type', models.CharField(choices=[('logo', 'Логотип'), ('banner', 'Баннер'), ('scheme', 'Схема'), ('gallery', 'Галерея Зображень')], max_length=125)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.image')),
                ('images_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.cinema')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='cinema',
            name='image',
            field=models.ManyToManyField(through='cinema.CinemaThourghtImage', to='common.image'),
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('description', models.TextField()),
                ('trailer', models.URLField()),
                ('type', models.CharField(choices=[('2D', '2D'), ('3D', '3D'), ('IMAX', 'IMAX')], default='2D', max_length=10, verbose_name='Формат фільму')),
                ('seoblock', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.seoblock')),
            ],
        ),
        migrations.CreateModel(
            name='FilmThourghtImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_type', models.CharField(choices=[('logo', 'Логотип'), ('banner', 'Баннер'), ('scheme', 'Схема'), ('gallery', 'Галерея Зображень')], max_length=125)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.image')),
                ('images_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.film')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='film',
            name='image',
            field=models.ManyToManyField(through='cinema.FilmThourghtImage', to='common.image'),
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('description', models.TextField()),
                ('seat_count', models.IntegerField()),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.cinema')),
                ('seoblock', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.seoblock')),
            ],
        ),
        migrations.CreateModel(
            name='HallThourghtImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_type', models.CharField(choices=[('logo', 'Логотип'), ('banner', 'Баннер'), ('scheme', 'Схема'), ('gallery', 'Галерея Зображень')], max_length=125)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.image')),
                ('images_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.hall')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='hall',
            name='image',
            field=models.ManyToManyField(through='cinema.HallThourghtImage', to='common.image'),
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.SmallIntegerField()),
                ('seat_num', models.SmallIntegerField()),
                ('hall_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.hall')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('start_time', models.TimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('film_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.film')),
                ('hall_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.hall')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField()),
                ('create_time', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.hall')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.seat')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.session')),
            ],
        ),
    ]
