# Generated by Django 5.2.8 on 2026-01-26 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cinema', '0001_initial'),
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cinema',
            name='seoblock',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.seoblock'),
        ),
        migrations.AddField(
            model_name='cinemathourghtimage',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.image'),
        ),
        migrations.AddField(
            model_name='cinemathourghtimage',
            name='images_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.cinema'),
        ),
        migrations.AddField(
            model_name='cinema',
            name='image',
            field=models.ManyToManyField(through='cinema.CinemaThourghtImage', to='common.image'),
        ),
        migrations.AddField(
            model_name='film',
            name='seoblock',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.seoblock'),
        ),
        migrations.AddField(
            model_name='filmthourghtimage',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.image'),
        ),
        migrations.AddField(
            model_name='filmthourghtimage',
            name='images_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.film'),
        ),
        migrations.AddField(
            model_name='film',
            name='image',
            field=models.ManyToManyField(through='cinema.FilmThourghtImage', to='common.image'),
        ),
        migrations.AddField(
            model_name='hall',
            name='cinema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.cinema'),
        ),
        migrations.AddField(
            model_name='hall',
            name='seoblock',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.seoblock'),
        ),
        migrations.AddField(
            model_name='booking',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.hall'),
        ),
        migrations.AddField(
            model_name='hallthourghtimage',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.image'),
        ),
        migrations.AddField(
            model_name='hallthourghtimage',
            name='images_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.hall'),
        ),
        migrations.AddField(
            model_name='hall',
            name='image',
            field=models.ManyToManyField(through='cinema.HallThourghtImage', to='common.image'),
        ),
        migrations.AddField(
            model_name='seat',
            name='hall_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.hall'),
        ),
        migrations.AddField(
            model_name='booking',
            name='seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.seat'),
        ),
        migrations.AddField(
            model_name='session',
            name='film_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.film'),
        ),
        migrations.AddField(
            model_name='session',
            name='hall_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.hall'),
        ),
        migrations.AddField(
            model_name='booking',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.session'),
        ),
    ]
