# Generated by Django 5.2.8 on 2026-02-14 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='end_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='film',
            name='start_time',
            field=models.DateField(),
        ),
    ]
