# Generated by Django 5.2.8 on 2026-03-02 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='create_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
