# Generated by Django 5.2.8 on 2026-01-26 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsStockModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('name_uk_ua', models.CharField(max_length=225, null=True)),
                ('name_ru', models.CharField(max_length=225, null=True)),
                ('description', models.TextField()),
                ('description_uk_ua', models.TextField(null=True)),
                ('description_ru', models.TextField(null=True)),
                ('trailer', models.URLField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('news', 'News'), ('stock', 'Stock')], max_length=10)),
                ('is_active', models.BooleanField(null=True)),
                ('seoblock', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.seoblock')),
            ],
            options={
                'db_table': 'news_newsstock',
            },
        ),
        migrations.CreateModel(
            name='NewsThourghtImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_type', models.CharField(choices=[('logo', 'Логотип'), ('banner', 'Баннер'), ('scheme', 'Схема'), ('gallery', 'Галерея Зображень')], max_length=125)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.image')),
                ('images_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.newsstockmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='newsstockmodel',
            name='image',
            field=models.ManyToManyField(through='news.NewsThourghtImage', to='common.image'),
        ),
    ]
