# Generated by Django 5.2.8 on 2026-01-26 18:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('main', 'main'), ('stock', 'stock')], default='main', max_length=10)),
                ('speed_button', models.CharField(choices=[('5', '5sec'), ('10', '10sec'), ('15', '15sec'), ('30', '30sec')], default='5', max_length=10)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='BackBannerThourghtImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_type', models.CharField(choices=[('logo', 'Логотип'), ('banner', 'Баннер'), ('scheme', 'Схема'), ('gallery', 'Галерея Зображень')], max_length=125)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.image')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BackgroundBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_image', models.BooleanField()),
                ('background_color', models.CharField(max_length=10)),
                ('image', models.ManyToManyField(through='page.BackBannerThourghtImage', to='common.image')),
            ],
        ),
        migrations.AddField(
            model_name='backbannerthourghtimage',
            name='images_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.backgroundbanner'),
        ),
        migrations.CreateModel(
            name='BannerThourghtImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_type', models.CharField(choices=[('logo', 'Логотип'), ('banner', 'Баннер'), ('scheme', 'Схема'), ('gallery', 'Галерея Зображень')], max_length=125)),
                ('url', models.URLField()),
                ('text', models.TextField(null=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.image')),
                ('images_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.banner')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='banner',
            name='image',
            field=models.ManyToManyField(through='page.BannerThourghtImage', to='common.image'),
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name=225)),
                ('adress', models.TextField()),
                ('coordinate', models.TextField()),
                ('seoblock', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.seoblock')),
            ],
        ),
        migrations.CreateModel(
            name='ContactThourghtImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_type', models.CharField(choices=[('logo', 'Логотип'), ('banner', 'Баннер'), ('scheme', 'Схема'), ('gallery', 'Галерея Зображень')], max_length=125)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.image')),
                ('images_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.contacts')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='contacts',
            name='image',
            field=models.ManyToManyField(through='page.ContactThourghtImage', to='common.image'),
        ),
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Главная страница', null=True)),
                ('data_create', models.DateTimeField(auto_now_add=True, null=True)),
                ('number_phone', models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator('\\+380\\d{9}$')])),
                ('seo_text', models.TextField(blank=True, null=True)),
                ('seo_text_uk_ua', models.TextField(blank=True, null=True)),
                ('seo_text_ru', models.TextField(blank=True, null=True)),
                ('seoblock', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.seoblock')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('name_uk_ua', models.CharField(max_length=20, null=True)),
                ('name_ru', models.CharField(max_length=20, null=True)),
                ('description', models.TextField()),
                ('description_uk_ua', models.TextField(null=True)),
                ('description_ru', models.TextField(null=True)),
                ('data_create', models.DateTimeField(auto_now_add=True, null=True)),
                ('type', models.CharField(choices=[('vip', 'VIP'), ('child', 'ChildRoom'), ('cafe', 'Cafe'), ('description', 'Description'), ('stock', 'Stock')], max_length=20)),
                ('is_active', models.BooleanField(null=True)),
                ('seoblock', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.seoblock')),
            ],
        ),
        migrations.CreateModel(
            name='PageThourghtImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_type', models.CharField(choices=[('logo', 'Логотип'), ('banner', 'Баннер'), ('scheme', 'Схема'), ('gallery', 'Галерея Зображень')], max_length=125)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.image')),
                ('images_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.page')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='page',
            name='image',
            field=models.ManyToManyField(through='page.PageThourghtImage', to='common.image'),
        ),
    ]
